services:
  pgvector:
    image: pgvector/pgvector:pg16
    container_name: pgvector
    user: "999:999" 
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data:Z,U
      #- ./conf/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      #- ./conf/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    environment:
      # POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres