services:
  minio:
    image: minio:latest
    container_name: minio
    user: "999:999" 
    restart: always
    environment:
      MINIO_ROOT_USER: minio_h2tzp6
      MINIO_ROOT_PASSWORD: minio_Sfh2Zr
      TZ: Asia/Shanghai
    volumes:
      - ./data:/data:Z,U
      - ./config:/root/.minio:Z,U
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001" --address ":9000"